### ISSUE TITLE
wlt build failled on css generation

### ISSUE THREAD

**Issue by natir** [eunomie/wlt#1]
When i run 

``` bash
mkdir test
cd test
wlt scaffold full
wlt build
```

I see : 

```
/home/pierre/Programation/Tools/wlt/lib/wlt.rb:41:in `block in css': uninitialized constant Sass::Engine (NameError)
    from /home/pierre/Programation/Tools/wlt/lib/wlt.rb:38:in `each'
    from /home/pierre/Programation/Tools/wlt/lib/wlt.rb:38:in `css'
    from /home/pierre/Programation/Tools/wlt/lib/wlt.rb:20:in `generate'
    from /home/pierre/Programation/Tools/wlt/libexec/wlt-build:13:in `<main>'
```

last git commit hash : 149178c7c99f52fc7
ruby version : ruby 2.0.0p353
OS : Fedora 20

Thank for your work.

**Comment by eunomie** [comment]
Hum, strange.
Which version of Sass gem is installed?
If you do a `bundle install` you should have a 3.2 version of sass. And it should works.
If you run a `bundle update` you'll have a 3.4 and I supposed this is the problem.

**Comment by natir** [comment]
Ok with sass 3.2 its run, with 3.4 all its broken.

Thanks
